name: "Archive dll"

on:
  workflow_dispatch:

jobs:
  Archive_dll:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update version
        run: |
          nowHash=$(git log -2 --format="%H" | tail -n 1)
          if [[ $nowHash != $(cat LASTCOMMIT_HASH) ]]; then
            echo $nowHash
            cat LASTCOMMIT_HASH
            targetname="Assembly-CSharp-$(date +'%Y%m%d%H%M').dll"
            echo $targetname
            curl -L "https://github.com/RavenfieldCommunity/HavenM/releases/download/Release/Assembly-CSharp.dll" -o $targetname
            echo "name=$targetname" > $GITHUB_ENV
            echo $nowHash > LASTCOMMIT_HASH
          fi
          ls

      - name: Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          tag_name: waow
          files: ${{env.name}}

      - name: Commit updated Time
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: Update hash
          file_pattern: LASTCOMMIT_HASH
