name: "Archive dll"

on:
  workflow_dispatch:

jobs:
  Archive_dll:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update version
        run: |
          echo "yes=no" > $GITHUB_ENV
          secondHash=$(git log -2 --format="%H" | tail -n 1)
          if [[ "$secondHash" != "$(cat LASTCOMMIT_HASH)" ]]; then
            echo $secondHash
            cat LASTCOMMIT_HASH
            targetname="Assembly-CSharp-$(date +'%Y%m%d%H%M').dll"
            echo $targetname
            curl -L "https://github.com/RavenfieldCommunity/HavenM/releases/download/Release/Assembly-CSharp.dll" -o $targetname
            echo "name=$targetname" > $GITHUB_ENV
            echo "$(git log -1 --format="%H")" > LASTCOMMIT_HASH
            echo "yes=yes" > $GITHUB_ENV
          fi
          ls

      - name: Release
        uses: softprops/action-gh-release@v2.2.2
        if: ${{env.yes}} == "yes"
        with:
          tag_name: waow
          files: ${{env.name}}

      - name: Commit updated Time
        uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{env.yes}} == "yes"
        with:
          branch: main
          commit_message: Update hash
          file_pattern: LASTCOMMIT_HASH

          