# .github/workflows/update-changelog.yaml
name: "Archive dll"

on:
  workflow_dispatch:

jobs:
  Update_Changelog:
    #aif: github.event.release.tag_name == 'Release'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update version
        run: |
          curl "https://github.com/RavenfieldCommunity/test/releases/download/d4/add.txt" -o add-temp.txt
          json=$(curl 'https://api.github.com/repos/RavenfieldCommunity/test/releases/latest' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: document' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36 Edg/135.0.0.0' -H 'sec-ch-ua: "Microsoft Edge";v="135", "Not-A.Brand";v="8", "Chromium";v="135"')
          fileUrl=$(echo $json | grep -o -P '(?<="updated_at": ").*?(?=")' - )	

          if [ $fileUrl != $(cat LAST_TM) ]; then
            naa="add-$(date +'%Y%m%d%H:%M').txt"
            rm add-temp.txt $naa
            echo "name=$naa" > $GITHUB_ENV
          fi
          echo "2" > LAST_TM

      - name: Commit updated Time
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: Update Time
          file_pattern: LAST_TM

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: waow
          files: ${{env.name}}
