name: "Archive dll"

on:
  workflow_dispatch:

jobs:
  Archive_dll:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update version
        run: |
          nowHash=$(git log -1 --format="%H")
          if [[ $nowHash != $(cat LASTCOMMIT_HASH) ]]; then
            echo $nowHash
            cat LASTCOMMIT_HASH
            targetname="add-$(date +'%Y%m%d%H%M').txt"
            echo $targetname
            curl "https://github.com/RavenfieldCommunity/test/releases/download/d4/GameLibs.Ravenfield.0.32.0.nupkg" -o $targetname
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Archiver ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -H "Content-Type: application/octet-stream" \
              "https://uploads.github.com/repos/RavenfieldCommunity/test/releases/222068261/assets?name=$targetname" \
              --data-binary $targetname
          fi
          echo "2" > LASTCOMMIT_HASH
          ls

      - name: Commit updated Time
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: Update hash
          file_pattern: LASTCOMMIT_HASH
