# .github/workflows/update-changelog.yaml
name: "Update Changelog"

on:
  release:
    types: [edited]

jobs:
  Update_Changelog:
    #aif: github.event.release.tag_name == 'Release'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update version
        run: |
          echo "\n## HavenM - ${{ github.event.release.body }}\n${{ github.event.release.assets[0].updated_at }}\n" >> 'CHANGELOG.md'

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.release.target_commitish }}
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md
